name: CI

on:
  push:
    branches: [ try ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Gitlab Registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.gitlab.com/tarantool/tarantool.io/try-cartridge:app

      - name: Run Ansible playbook to deliver new Tarantool image to the server
        uses: dawidd6/action-ansible-playbook@v2.2.0
        with:
          playbook: deploy.yml
          directory: deploy
          requirements: requirements.yml
          key: ${{secrets.SSH_KEY}}
          inventory: |
            [all]
            try-cartridge.tarantool.io

            [all:vars]
            ansible_user=${{secrets.ANSIBLE_USERNAME}}
            ansible_ssh_user=${{secrets.ANSIBLE_USERNAME}}
          options:
            -e GITLAB_USERNAME=${{secrets.GITLAB_USERNAME}}
            -e GITLAB_PASSWORD=${{secrets.GITLAB_PASSWORD}}
            -e SENTRY_DSN=${{secrets.SENTRY_DSN}}
            -e SENDGRID_API_KEY=${{secrets.SENDGRID_API_KEY}}
            -e RECAPTCHA_PRIVATE_KEY=${{secrets.RECAPTCHA_PRIVATE_KEY}}
            -e RECAPTCHA_PUBLIC_KEY=${{secrets.RECAPTCHA_PUBLIC_KEY}}
            -e DATABASE_URL=${{secrets.DATABASE_URL}}
            --timeout 60
